apiVersion: apps/v1
kind: Deployment
metadata:
  name: nams-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nams-app
  template:
    metadata:
      labels:
        app: nams-app
    spec:
      containers:
        - name: nams-app
          image: gcr.io/terraform-449405/nams-app:latest  # Jenkins will replace this line with the correct tag
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV
